mysite/blog/urls.py
from django.conf.urls import url
from . import views

urlpatterns=[
    url(r"^$",views.anasayfa, name="anasayfa"),
    url(r"^post/(?P<id>\d+)/duzenle/$",views.post_düzenle,name="duzenle"),
    url(r'^post/(?P<id>\d+)/$',views.icerik,name="icerik"),
    url(r"^post/add/$",views.yeni_post,name="yeni_post"),
    url(r"^post/(?P<id>\d+)/sil/$",views.sil,name="sil"),
    url(r"^kayit/$", views.kayit, name="kayit"),
    url(r"^giris/$",views.giris, name="giris"),
    url(r"^cıkıs/$",views.cıkıs,name="cıkıs"),
]

mysite/mysite/urls.py
from django.conf.urls import include
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('blog.urls')),
]

mysite/blog/models.py
from django.db import models
from django.urls import reverse
class Post(models.Model):
    baslik = models.CharField(max_length=200)
    icerik = models.TextField()
    tarih = models.DateTimeField(auto_now_add=True)

    def get_absolute_url(self):
        return reverse('icerik', kwargs={'id': self.id})

    def __str__(self):
        return self.baslik
# Create your models here.

mysite/blog/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ("baslik","icerik")

mysite/blog/views.py
from django.shortcuts import render,get_object_or_404, redirect, HttpResponseRedirect
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth import login, logout
from .models import Post
from .forms import PostForm
from django.utils import timezone
from django.contrib import messages
from django.urls import reverse

def post_düzenle(request,id):
    post = get_object_or_404(Post, id=id)
    form = PostForm(request.POST or None, instance=post)
    if form.is_valid():
        form.save()
        messages.success(request, "Başarılı bir şekilde güncellediniz.",'alert alert-success')
        return HttpResponseRedirect(post.get_absolute_url())
    return render(request,"blog/yeni_post.html",{ "form":form })

def yeni_post(request):
    form = PostForm(request.POST or None)
    if(form.is_valid()):
        post = form.save()
        messages.success(request,"Başarılı bir şekilde oluşturdunuz.")
        return HttpResponseRedirect(post.get_absolute_url())
    return render(request,"blog/yeni_post.html",{"form":form})

def sil(request,id):
    post = get_object_or_404(Post, id=id)
    post.delete()
    return redirect("anasayfa")

def anasayfa(request):
    posts= list(reversed(Post.objects.all()))
    return render(request,"blog/anasayfa.html",{"posts":posts})

def icerik(request,id):
    post=get_object_or_404(Post,id=id)
    return render(request,"blog/icerik.html",{"post":post})

def giris(request):
    form = AuthenticationForm()
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            login(request, form.get_user())
            return redirect(reverse('anasayfa'))
        else:
            raise request.ValidationError("Şifre veya kullanıcı adı yanlış!")
    return render(request,"blog/log_in.html",{"form":form,"urlsi":reverse("kayit")})

def kayit(request):
    form = UserCreationForm()
    if request.method == 'POST':
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse('example:log_in'))
        else:
            print(form.errors)
    return render(request,"blog/kayıt.html",{"form":form,"urlsi":reverse("giris")})

def cıkıs(request):
    logout(request)
    return redirect(reverse("giris"))
# Create your views here.

mysite/blog/templates/base.html
{%load static%}

<!DOCTYPE html>

<html>
<head>
    <meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}| Hasser {% endblock%} </title>
    <link rel="stylesheet" href=https://getbootstrap.com/docs/4.1/dist/css/bootstrap.min.css>
    <link rel="icon" href="https://www.blogger.com/about/favicon/favicon-96x96.png">
</head>
<body>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="https://getbootstrap.com/docs/4.1/assets/js/vendor/popper.min.js"></script>
        <script src="https://getbootstrap.com/docs/4.1/dist/js/bootstrap.min.js"></script>

    {% include "header.html" %}
    <div class="container" style="margin-top: 50px">
    {% include "messages.html" %}

    {%block body%}

    {% endblock body%}
</div>
</body>
</html>

mysite/blog/templates/blog/anasayfa.html
{% extends 'base.html'%}
{% block title%}
Anasayfa {{block.super}}
{%endblock%}

{% block body %}
{# {{ post.get_absolute_url }} #}
{% for post in posts %}
<div class="card">
	<div class="card-header">
	<div class=baslik style="margin-left: 15px">
	<h1>
	<a href="{% url 'icerik' id=post.id %}">
	{{ post.baslik }}
	</a>
	</h1>
	</div>
	<div class=tarih align="right" style="margin-left: 15px">
	<sub>
	 {{ post.tarih }}
	</sub>
	</div>
	</div>
	<div class="card-body">
	<div id="{{post.id}}yazi" style="margin-left: 15px">{{ post.icerik }}</div><br></div>
	<button id="{{post.id}}" class="btn btn-light">Tümünü göster</button>
	<div class="card-footer">
	<a href="{% url 'icerik' id=post.id %}" class="btn btn-success">İncele</a>
	<a href="{% url 'sil' id=post.id %}" class="btn btn-danger">Sil</a>
	<a href="{% url 'duzenle' id=post.id %}" class="btn btn-primary">Düzenle</a>
</div></div>
<script>
	var metin="";
	var ilkyuz="";
	var metin="{{ post.icerik }}";
	var postid="{{post.id}}"
	var ilkyuz="{{ post.icerik|truncatewords:30 }}";
	$("#{{post.id}}yazi").text(ilkyuz);
	$("#{{post.id}}yazi").html(ilkyuz+"<div id='"+postid+"sonrası'>"+metin.substring(200)+"</div>");
	$("#{{post.id}}sonrası").fadeOut(0)
/*	$(document).ready(function(){
		//var metin=$("#{{post.id}}yazi").text();
		//var ilkyuz=metin.substring(0,100);
		$("#{{post.id}}yazi").text(ilkyuz)
	})*/
	$("#{{post.id}}").click(function(){
		$("#{{post.id}}").fadeOut(0)
		$("#{{post.id}}sonrası").fadeIn(400)
		/*if($("#{{post.id}}yazi").text()==ilkyuz){
			$("#{{post.id}}yazi").text(metin);
		}
		else{
			$("#{{post.id}}yazi").text(ilkyuz);
		}*/

	})
</script>
{% empty %}
<div class="container">
	<h1>
		Hiç Post yazılmadı.
	</h1>
</div>
{% endfor %}
{% endblock%}

mysite/blog/templates/blog/icerik.html
{%extends 'base.html'%}
{% block title %}
{{post.baslik}} | {{ block.super }}
{% endblock %}
    {% block body%}
        <h1>{{ post.baslik }}</h1><br>
        {{ post.tarih }}<br>
        {{ post.icerik }}<br>
    {%endblock%}
</body>
</html>

mysite/blog/templates/blog/kayıt.html
{% extends 'base.html' %}

{% block title %}
Kayıt Ol {{block.super}}
{% endblock %}

{% block body %}
<div class="card bg-dark text-white">
<div class="card-body">
  <form method="post">
    {% csrf_token %}
    {% for field in form %}
      <div>
        {{ field.label_tag }}
        {{ field }}
      </div>
    {% endfor %}
    <button type="submit" class="btn btn-light">Kayıt Ol</button>
  </form>
</div>
</div>
  <p> Hesabın var mı? <a href="{{urlsi}}">Giriş Yap</a></p>
<script>
    $("#id_username").attr("class","form-control")
    $("#id_password1").attr("class","form-control")
    $("#id_password2").attr("class","form-control")
</script>
{% endblock body %}

mysite/blog/templates/blog/log_in.html
{% extends 'base.html' %}
{% block title %}
Giriş Yap {{block.super}}
{% endblock %}


{% block body %}
<div class="card bg-dark text-white">
<div class="card-body">
  <form method="post">
    {% csrf_token %}
    {% for field in form %}
{{ field.label_tag }}
{{ field }}
    {% endfor %}
    <button type="submit" class="btn btn-light">Giriş Yap</button>
  </form>
  </div>
  </div>
  <p>Hesabın yok mu? <a href="{{urlsi}}">Kayıt Ol</a></p>
<script>
    $("#id_username").attr("class","form-control")
    $("#id_password").attr("class","form-control")
</script>
{% endblock body %}

mysite/blog/templates/blog/yeni_post.html
{% extends 'base.html'%}
{% block title%}
Form {{block.super}}
{%endblock%}

{% block body %}
    <h1>
        Form
    </h1>
    
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-secondary">Kaydet</button>
    </form>
    <script>
    $(document).ready(function(){
    $("#id_baslik").attr("class","form-control")
    $("#id_icerik").attr("class","form-control")
    $("#id_icerik").attr("row","15")
    })
    </script>
{% endblock %}

mysite/blog/templates/header.html
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-warning bg-inverse">
<a class="navbar-brand" href="{% url 'anasayfa' %}">Blog</a>
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample04" aria-controls="navbarsExample04" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarsExample04">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'anasayfa' %}"> Anasayfa <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'yeni_post' %}"> Post ekle </a>
        </li>
        {% if request.user.is_authenticated%}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'cıkıs'%}"> Çıkış Yap </a>
        </li>
        {% else %}
        <li class="nav-item justify-content-md-right">
          <a class="nav-link" href="{% url 'giris' %}"> Giriş Yap </a>
        </li>
        <li class="nav-item">
          <a class="nav-link justify-content-md-right" href="{% url 'kayit' %}"> Kayıt Ol </a>
        </li>
        {% endif %}
      </ul>
    </div>
</div>
</nav>

mysite/blog/templates/messages.html
{% if messages %}
    {% for message in messages %}
    <div style="margin: 24px 0">
    <div {% if message.tags %} class="{{ message.tags }} alert alert-success fade in alert-dismissible show"{% endif %}>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true" style="font-size: 20px">×</span>
        </button>
        {{ message }}</div>
    </div>
    {% endfor %}
{% endif %}